# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-31 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
