# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_email_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('decription', models.TextField()),
                ('facebook', models.CharField(blank=True, max_length=250)),
                ('twitter', models.CharField(blank=True, max_length=250)),
                ('instagram', models.CharField(blank=True, max_length=250)),
                ('youtube', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='NicheList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nichename', models.CharField(max_length=250)),
                ('nichedescription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('influencers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Influencer')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.NicheList')),
            ],
        ),
        migrations.AddField(
            model_name='nichelist',
            name='influencers',
            field=models.ManyToManyField(through='search.OrderedList', to='search.Influencer'),
        ),
    ]
