# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180805_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
